version: "3.9"

services:
  usuarios:
    build:
      context: ./tcg-usuarios
      dockerfile: Dockerfile
    container_name: tcgshop-usuarios
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_APP_NAME: tcg_usuarios

      DB_URL: "jdbc:mysql://172.31.28.221:3306/tcg_usuarios?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      DB_USERNAME: "tcguser"
      DB_PASSWORD: "TcgPass123!"
      DB_DRIVER: "com.mysql.cj.jdbc.Driver"

      JPA_DDL_AUTO: "update"
      JPA_SHOW_SQL: "false"
      JPA_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
      JPA_FORMAT_SQL: "false"

      JWT_SECRET: "ClaveSecreta123"
      JWT_EXPIRATION: 86400000

      CORS_ALLOWED_ORIGINS: "*"

      SERVER_ERROR_INCLUDE_MESSAGE: "always"
      SERVER_ERROR_INCLUDE_STACKTRACE: "never"
